---
abstract: 'Abstract translucent attribute management.'
author:
  - 'Kevin Cody-Little <kcody@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Attrib
no_index:
  directory:
    - t
    - inc
requires:
  Class::Multi: 1.01
resources:
  repository: https://github.com/kcodyjr/class-attrib
version: 1.04
