# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Attrib
version:      1.06
version_from: Attrib.pm
installdirs:  site
requires:
    Carp:                          0
    Class::Multi:                  1.02
    Storable:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
